---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
  - package-ecosystem: npm
    directory: "/core"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
