image:
  file: .gitpod.Dockerfile

tasks:
  - init: go get -d ./...
    command: curl -fsSL https://secman-team.github.io/install.sh | bash

vscode:
  extensions:
    - pkief.material-icon-theme
    - esbenp.prettier-vscode
    - golang.go
