image:
  file: Dockerfile

tasks:
  - init: git config pull.ff only && cd core && go get && cd ..
    command: go build

vscode:
  extensions:
    - foxundermoon.shell-format@7.0.1:dJqOSN173jVh12b+ScTqtw==
    - pkief.material-icon-theme@4.5.0:ckDTVCTpdr4G0ZmIlQWkZA==
