before:
  hooks:
    - go mod download
    - go generate ./...
    - curl -fsSL https://raw.githubusercontent.com/abdfnx/verx/HEAD/install.sh | bash

env:
  - GO111MODULE=on

builds:
  -
    id: "secman"

    main: ./core/core.go

    # Binary name.
    # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
    # Default is the name of the project directory.
    binary: secman

    env:
      - CGO_ENABLED=0
      - Version=$(verx secman-team/secman -l)

    ldflags:
     - -X main.build={{.Env.Version}}

    goos:
      - windows
      - darwin
      - linux

    goarch:
      - amd64
      - arm
      - arm64

    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
