env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  -
    id: "secman"

    main: ./core/core.go

    # Binary name.
    # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
    # Default is the name of the project directory.
    binary: secman

    ldflags:
     - -s -w -X main.build=v{{.Version}}

    env:
      - CGO_ENABLED=0

    goos:
      - freebsd
      - windows

    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - 6
      - 7

    gomips:
      - hardfloat
      - softfloat

    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
      - goarm: mips64
        gomips: hardfloat

    gobinary: "go1.13.4"
    mod_timestamp: '{{ .CommitTimestamp }}'
    skip: false

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
