project_name: secman

env:
  - CGO_ENABLED=0

release:
  prerelease: auto
  draft: true
  name_template: "Secman {{ .Tag }}"

before:
  hooks:
    - go mod tidy -compat=1.17

builds:
  - <<: &build_defaults
      binary: bin/secman
      main: ./
      ldflags:
        - -X main.version={{ .Tag }}
        - -X main.buildDate={{ .Env.BuildDate }}

    id: macos
    goos: [ darwin ]
    goarch: [ amd64, arm64, arm ]

  - <<: *build_defaults
    id: linux
    goos: [ linux ]
    goarch: [ amd64, arm64, arm, 386 ]

  - <<: *build_defaults
    id: windows
    goos: [ windows ]
    goarch: [ amd64, arm64, arm, 386 ]

  - <<: *build_defaults
    id: freebsd
    goos: [ freebsd ]
    goarch: [ amd64, arm64, arm, 386 ]

archives:
  - id: nix
    builds: [ macos, linux, freebsd ]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Tag }}_{{ .Arch }}"

    wrap_in_directory: "true"
    replacements:
      darwin: macos
    format: zip
    files:
      - LICENSE

  - id: windows
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: "false"
    format: zip
    files:
      - LICENSE

nfpms:
  - license: MIT
    maintainer: secman
    homepage: https://secman.dev
    bindir: /usr
    file_name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Arch }}"
    description: "👊 Human-friendly and amazing TUI secrets manager"
    formats:
      - apk
      - deb
      - rpm

brews:
  - goarm: 6
    tap:
      owner: scmn-dev
      name: homebrew-tap
    homepage: "https://secman.dev"
    description: "👊 Human-friendly and amazing TUI secrets manager"
    license: MIT
    post_install: system "npm install --global @secman/scc"

scoop:
  url_template: "https://github.com/scmn-dev/secman/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

  bucket:
    owner: scmn-dev
    name: scoop

  homepage: "https://secman.dev"
  description: "👊 Human-friendly and amazing TUI secrets manager"

  license: MIT

  post_install: ["npm install --global @secman/scc"]

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Version }}-next"
