project_name: secman

env_files:
  github_token: ~/gh-goreleaser-token.txt

release:
  prerelease: auto
  draft: true
  name_template: "Secman v{{ .Version }}"

before:
  hooks:
    - go mod tidy

builds:
  - <<: &build_defaults
      binary: bin/secman
      main: ./core
      ldflags:
        - -X main.version=v{{ .Version }}
        - -X main.versionDate=(31-05-2021)

    id: macos
    goos: [ darwin ]
    goarch: [ amd64 ]

  - <<: *build_defaults
    id: linux
    goos: [ linux ]
    goarch: [ 386, arm, amd64, arm64 ]
    env:
      - CGO_ENABLED=0

  - <<: *build_defaults
    id: windows
    goos: [ windows ]
    goarch: [ 386, amd64 ]

archives:
  - id: nix
    builds: [ macos, linux ]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Os }}_v{{ .Version }}_x64"

    wrap_in_directory: true
    replacements:
      darwin: macos
    format: zip
    files:
      - LICENSE
      - ./share/man/man1/secman.1

  - id: windows
    builds: [ windows ]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE

nfpms:
  - license: MIT
    maintainer: Secman
    homepage: https://github.com/secman-team/secman
    bindir: /usr
    dependencies:
      - git
    description: The Password Manager of your Dreams.
    formats:
      - deb
      - rpm
    files:
      "./share/man/man1/secman.1": "/usr/share/man/man1"
