# https://taskfile.dev

version: "3"

vars:
  SECMAN_UNIX_PATH: /usr/local/bin

tasks:
  default:
    cmds:
      - task: build
      - yarn build

  set-tag-and-date:
    cmds:
      - if [ -f "date.txt" ]; then rm date.txt; fi
      - if [ -f "tag.txt" ]; then rm tag.txt; fi
      - go run ./scripts/date.go >> date.txt
      - git describe --abbrev=0 --tags >> tag.txt

  remove:
    cmds:
      - sudo rm -rf "{{ .SECMAN_UNIX_PATH }}"/secman

  install:
    cmds:
      - sudo mv secman "{{ .SECMAN_UNIX_PATH }}"

  build:
    cmds:
      - task: set-tag-and-date
      - go mod tidy -compat=1.18
      - go build -ldflags "-X main.version=$(cat tag.txt) -X main.buildDate=$(cat date.txt)" -o secman

  build-scc:
    dir: ./scc
    cmds:
      - if ! [ -d ./node_modules ]; then yarn; fi
      - yarn build

  build-smui:
    dir: ./hub
    cmds:
      - task: set-tag-and-date
      - yarn build
      - mv dist ui
      - cp tag.txt ui
      - zip -9 -r smui.zip ui

  link-scc:
    dir: ./scc
    cmds:
      - npm link

  publish-scc:
    dir: ./scc
    cmds:
      - yarn publish

  test:
    cmds:
      - yarn dev

  bfs:
    desc: build from source
    cmds:
      - task: build
      - task: build-scc
      - task: link-scc
      - task: install
