# https://taskfile.dev

version: "3"

vars:
  SECMAN_UNIX_PATH: /usr/local/bin

tasks:
  default:
    cmds:
      - task: build
      - yarn build

  setup:
    cmds:
      - if [ -f "date.txt" ]; then rm date.txt; fi
      - if [ -f "tag.txt" ]; then rm tag.txt; fi
      - task: fix-vercel-go-mod
      - go run ./scripts/date.go >> date.txt
      - git describe --abbrev=0 --tags >> tag.txt

  export-node-options:
    cmds:
      - export NODE_OPTIONS=--openssl-legacy-provider

  remove:
    cmds:
      - sudo rm -rf "{{ .SECMAN_UNIX_PATH }}"/secman

  install:
    cmds:
      - sudo mv secman "{{ .SECMAN_UNIX_PATH }}"

  release:
    cmds:
      - task: node_checks
      - BuildDate="$(cat date.txt)" goreleaser release --rm-dist --timeout 100m

  build:
    cmds:
      - task: setup
      - go mod tidy -compat=1.18
      - go build -ldflags "-X main.version=$(cat tag.txt) -X main.buildDate=$(cat date.txt)" -o secman

  build-scc:
    dir: ./scc
    cmds:
      - if ! [ -d ./node_modules ]; then yarn; fi
      - yarn build

  build-smui:
    dir: ./hub
    cmds:
      - task: setup
      - yarn build
      - mv dist ui
      - cp ../tag.txt ui
      - zip -9 -r smui.zip ui

  link-scc:
    dir: ./scc
    cmds:
      - npm link

  publish-scc:
    dir: ./scc
    cmds:
      - yarn publish

  test:
    cmds:
      - yarn dev

  deploy:
    cmds:
      - yarn deploy

  bfs:
    desc: build from source
    cmds:
      - task: build
      - task: build-scc
      - task: link-scc
      - task: install

  upload-scoop-manifest:
    cmds:
      - git clone https://github.com/scmn-dev/scoop
      - cd scoop
      - rm secman.json
      - cp ../dist/secman.json .

  node_checks:
    cmds:
      - if ! [ -d ./node_modules ]; then yarn; fi
      - task: fix-vercel-go-mod

  fix-vercel-go-mod:
    cmds:
      - if [ -d "node_modules" ]; then if ! [ -f "node_modules/@vercel/go/go.mod" ]; then touch node_modules/@vercel/go/go.mod; fi; fi
