version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  win: circleci/windows@2.2.0
  docker: circleci/docker@1.4.0

linux_environment: &linux_environment
  PLATFORM: "linux"

windows_environment: &windows_environment
  PLATFORM: "windows"

install_gh: &install_gh
  name: Install Github CLI
  command: |
    brew install gh

install_secman_linux: &install_secman_linux
  name: Install Secman (Linux)
  command: curl -fsSL https://secman-team.github.io/install.sh | bash

install_secman_windows: &install_secman_windows
  name: Install Secman (Windows)
  command: iwr -useb https://secman-team.github.io/install.ps1 | iex

test_secman: &test_secman
  name: Run Secman && Test It
  command: |
    git clone https://github.com/secman-team/.secman.ex $HOME/.secman
    secman

jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -d ./...

  linux_build:
    environment:
      <<: *linux_environment

    machine:
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - docker/pull:
          images: 'homebrew/brew'
      - run:
          <<: *install_gh
      - run:
          <<: *install_secman_linux

  linux_test:
    environment:
      <<: *linux_environment

    machine:
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - docker/pull:
          images: 'homebrew/brew'
      - run:
          <<: *install_gh
      - run:
          <<: *install_secman_linux
      - run:
         <<: *test_secman

  windows_build:
    environment:
      <<: *windows_environment

    executor: win/default

    steps:
      - checkout
      - run:
          <<: *install_secman_windows
          shell: powershell.exe

  windows_test:
    environment:
      <<: *windows_environment

    executor: win/default

    steps:
      - checkout
      - run:
          <<: *install_secman_windows
          shell: powershell.exe

      - run:
          <<: *test_secman
          shell: powershell.exe

workflows:
  version: 2.1
  linux_jobs:
    jobs:
      - linux_build
      - linux_test

  windows_jobs:
    jobs:
      - windows_build
      - windows_test
