version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  win: circleci/windows@2.2.0

linux_environment: &linux_environment
  PLATFORM: "linux"

windows_environment: &windows_environment
  PLATFORM: "windows"

jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -d ./...

  linux_build:
    environment:
      <<: *linux_environment

    machine:
      # linux VM
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run:
          name: Install Secman (Linux)
          command: |
            curl -fsSL https://secman-team.github.io/install.sh | bash
  
  linux_test:
    environment:
      <<: *linux_environment
    
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run:
          name: Run Secman && Test It
          command: |
            secman
            git clone https://github.com/secman-team/.secman.ex ~/.secman
            secman

  windows_build:
    environment:
      <<: *windows_environment

    executor: win/default

    steps:
      - checkout
      - run:
          name: Install Secman (Windows)
          command: iwr -useb https://secman-team.github.io/install.ps1 | iex
          shell: powershell.exe
  
  windows_test:
    environment:
      <<: *windows_environment
    
    executor: win/default

    steps:
      - checkout
      - run:
          name: Run Secman && Test It
          command: |
            secman
            git clone https://github.com/secman-team/.secman.ex ~/.secman
            secman
          shell: powershell.exe

workflows:
  version: 2.1
  linux_jobs:
    jobs:
      - linux_build
      - linux_test
  
  windows_jobs:
    jobs:
      - windows_build
      - windows_test
