project_name: secman

release:
  github:
    owner: secman-team
    name: secman
  name_template: '{{.Tag}}'

milestones:
- repo:
    owner: secman-team
    name: secman
  name_template: '{{ .Tag }}'

scoop:
  name: secman
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  commit_msg_template: Scoop update for {{ .ProjectName }} version {{ .Tag }}

builds:
- id: secman

  goos:
  - linux
  - darwin

  goarch:
  - amd64
  - arm64
  - "386"

  goarm:
  - "6"
  targets:
  - linux_amd64
  - linux_arm64
  - linux_386
  - darwin_amd64
  dir: .
  main: .
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    -X main.builtBy=goreleaser
  binary: secman
  lang: go
  gobinary: go

archives:
- id: default
  builds:
  - secman
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
  format: tar.gz
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
  allow_different_binary_count: false

snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT-{{ .ShortCommit }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

dist: dist

env_files:
  github_token: ~/.config/goreleaser/github_token

source:
  name_template: '{{ .ProjectName }}-{{ .Version }}'
  format: tar.gz

github_urls:
  download: https://github.com
