name: Secman Build CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 17

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Run Tests
        run: |
          ./bin/run -h
          ./bin/run init
          ./bin/run crypto --sha256 "Hello World"
