name: Docker Image CI (VM)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CID: CID=$(docker create -t -i abdcodedoc/secman:vm) >> .sm_docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./api/vm/Dockerfile --tag abdcodedoc/secman:vm
  
  run:
    needs: [build]
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the Docker image
        run: |
          source .sm_docker
          docker start -a -i $CID
