name: Secman Docker CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  DOCKERHUB_IMAGE: smcr/secman
  GHCR_IMAGE: ghcr.io/secman-team/secman

jobs:
  # DockerHub
  dockerhub_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_SECMAN_TOKEN }}

      - name: Run Build
        run: |
          docker pull $DOCKERHUB_IMAGE:latest
          git clone https://github.com/secman-team/secman-docker
          docker build -t $DOCKERHUB_IMAGE --cache-from $DOCKERHUB_IMAGE:latest --file ./secman-docker/Dockerfile .
          docker push $DOCKERHUB_IMAGE

  dockerhub_run:
    needs: [ dockerhub_build ]

    runs-on: ubuntu-20.04

    container:
      image: smcr/secman:latest

    steps:
      - name: Run Secman in Docker Container
        run: |
          secman

  # GitHub Packages
  ghcr_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Login to Github Packages
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Run Build
        run: |
          docker pull $GHCR_IMAGE:latest
          git clone https://github.com/secman-team/secman-docker
          docker build -t $GHCR_IMAGE --cache-from $GHCR_IMAGE:latest --file ./secman-docker/Dockerfile .
          docker push $GHCR_IMAGE

  ghcr_run:
    needs: [ ghcr_build ]

    runs-on: ubuntu-20.04

    container:
      image: ghcr.io/secman-team/secman:latest

    steps:
      - name: Run Secman in Github Docker Container
        run: |
          secman
