name: Secman Docker Image CI (VM)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v2
    - run: docker build . --file ./api/vm/Dockerfile --tag abdcodedoc/secman:vm
    
    - name: Push the Docker image
      uses: actions/checkout@v2
    - run: docker push abdcodedoc/secman:vm
  
  run:
    needs: [ build ]
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the Docker image
        run: |
          CID=$(docker create -t -i abdcodedoc/secman:vm)
          docker start -a -i $CID
