name: Secman Docker CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  IMAGE: smcr/secman

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Log into registry
        run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Run Build
        run: |
          docker pull $IMAGE:latest
          git clone https://github.com/secman-team/secman-docker
          docker build -t $IMAGE --cache-from $IMAGE:latest --file ./secman-docker/Dockerfile .
          docker push $IMAGE

  run:
    needs: [ build ]

    runs-on: ubuntu-20.04
    
    container:
      image: smcr/secman:latest

    steps:
      - name: Run Secman in Docker Container
        run: |
          secman
