name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
        make
        make setup

    - name: Run the New Build (Without Authentication)
      run: secman

    - name: Run the New Build (With Authentication)
      run: |
        secman auth login --with-token ${{ secrets.ACCESS_TOKEN }}
        secman
