name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CLONE_DOT_SMCLUSTER: git clone https://github.com/scmn-dev/sm-cluster ~/.sm-cluster

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
        make
        make setup

    - name: Run the New Build (Without Authentication)
      run: |
        $CLONE_DOT_SMCLUSTER
        secman

    - name: Run the New Build (With Authentication)
      run: |
        $CLONE_DOT_SMCLUSTER
        echo ${{ secrets.ACCESS_TOKEN }} >> token.txt
        secman auth login --with-token < token.txt
        secman
