name: Pack

on:
  workflow_dispatch:
    inputs:
      release:
        description: "The New Secman Release"
        required: true

env:
  RELEASE: ${{ github.event.inputs.release }}

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn

      - name: Pack
        run: |
          yarn pack

      - name: Upload It
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.RELEASE }}
          files: ./dist/secman-v${{ env.RELEASE }}/secman-v${{ env.RELEASE }}-linux-x64.tar.gz

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn

      - name: Pack
        run: yarn pack:win
