name: Release

on:
  push:
    tags:
      - "*"

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  GITHUB_ACTIONS_NAME: "github-actions[bot]"
  GITHUB_ACTIONS_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"

permissions: write-all

jobs:
  build-secman:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16

      - name: Set up Task
        uses: arduino/setup-task@v1

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true

      - name: Set up Build Info
        run: task setup

      - name: Set up Tag
        id: ghtag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build
        env:
          TAG: ${{ steps.ghtag.outputs.tag }}
        run: |
          task release
          task upload-scoop-manifest
          cd ./scoop
          git config --local user.email "${{ env.GITHUB_ACTIONS_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_ACTIONS_NAME }}"
          git diff --cached
          git add .
          git commit -m "Scoop update for secman version ${TAG}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: "scmn-dev/scoop"
          github_token: ${{ secrets.ACCESS_TOKEN }}
          directory: ./scoop

      - name: Build SMUI
        run: task build-smui

      - name: Upload SMUI
        uses: softprops/action-gh-release@v1
        with:
          files: hub/smui.zip
