name: Release (.deb)

on:
  workflow_dispatch:
    inputs:
      release:
        description: "The New Secman Release"
        required: true

env:
  RELEASE: ${{ github.event.inputs.release }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2.4.0
      with:
        node-version: 16

    - name: Install Dependencies
      run: yarn

    - name: Build
      run: |
        sudo yarn pack:deb
        sudo mv ./dist/deb/secman_${{ env.RELEASE }}-1_amd64.deb ./dist/deb/secman_v${{ env.RELEASE }}_amd64.deb

    - name: Upload It
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/deb/secman_v${{ env.RELEASE }}_amd64.deb
