name: Secman CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install secman
        run: curl -fsSL https://secman-team.github.io/install.sh | bash

      - name: Clone .secman (ex folder)
        run: git clone https://github.com/secman-team/.secman.ex ~/.secman

      - name: Run secman
        run: secman
